name: PR Labeled

on:
  pull_request_target:
    types: [labeled]

jobs:
  status-label-to-lwip:
    runs-on: ubuntu-latest
    name: Check to see if LWIP update is needed
    container:
      image: ponylang/shared-docker-ci-release:20191107
    steps:
      - uses: actions/checkout@v2
      - run: bash .ci-scripts/pr-label.bash
        env:
          API_CREDENTIALS: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
